language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator
xcode_workspace: Toolbelt.xcworkspace
xcode_scheme: Toolbelt
before_install: gem install xcpretty slather -N
after_success: slather
