fastlane_version "1.100.0"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Do a patch release"
  lane :release_patch do
    test
    
    increment_build_number
    increment_version_number(
      bump_type: "patch"
    )
    version_bump_podspec(
      path: "Toolbelt.podspec",
      bump_type: "patch"
    )

    release

  end


  desc "Build and release a new pod version"
  lane :release do

    pod_lib_lint
    # pod_push
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
