fastlane_version "1.100.0"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build and release a new pod version"
  lane :release do

    test
    # ensure_git_status_clean
    
    # increment_build_number(
    #   xcodeproj: "Denver.xcodeproj"
    # )

    # increment_version_number(
    #   xcodeproj: "Denver.xcodeproj",
    #   bump_type: "patch"
    # )

    # commit_version_bump(
    #   xcodeproj: 'Denver.xcodeproj'
    # )

    # # Update code signing credentials
    # match(type: "appstore") # more information: https://codesigning.guide

    # # Builds
    # gym(
    #   scheme: "Denver",
    #   use_legacy_build_api: true 
    # )

    # # Testflight
    # pilot(
    #   skip_waiting_for_build_processing: true,
    #   changelog: changelog_from_git_commits
    # )

    # # Tag
    # add_git_tag
    # # Push
    # push_to_git_remote(
    #   tags: true
    # )

    # # To the moon!
    # rocket

  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
